### ISSUE TITLE
Buttons stop working

### ISSUE THREAD

**Issue by ITensEI** [fredemmott/StreamDeck-Discord#3]
I installed plugin yesterday. Setup the buttons with the API keys. Worked fine when I tested.
Next day (and a power cycle later) they no longer work. Pressing them shows yellow triangle. I rechecked the keys etc. I re-installed the plugin and the keys still not working.

**Comment by Conroy1988** [comment]
I also have this same issue

**Comment by ARTdrakon** [comment]
Same issue, used this since 1.0 and it broke today.

**Comment by eliasthompson** [comment]
It could be related to this other issue if it stopped working after a computer restart. I had similar symptoms and the temp fix mentioned [here](https://github.com/fredemmott/StreamDeck-Discord/issues/2#issue-406590497) worked for me.

**Comment by ITensEI** [comment]
For me I never managed to get it to work again. I reinstalled the plugin and made sure the API key is correct. I just get a yellow triangle and nothing else. Every time I boot my computer Discord asks me to authorize the plugin, but still won't work after. For now it's just unusable so I deleted it until it's fixed.

**Comment by eliasthompson** [comment]
The only other thing I'd recommend is recreating the registered application with discord again and going through that process. If that doesn't work then I got nothin'.

**Comment by fredemmott** [comment]
The 4.1 stream deck software is out today, and adds real support for multi-action configuration. Hopefully migrating to that will fix this issue, and I’ll try to get that done in the next few days.

If that doesn’t do it, I’m not really sure how to debug this without having a way to reproduce the problem myself; though:

- how many discord actions do you have?
- do you have multiple stream decks?

**Comment by fredemmott** [comment]
Also, do you use folders? I just added my first and made it break once, but I can’t figure out how to break it again

**Comment by eliasthompson** [comment]
My Discord buttons reside in a folder one layer down. At one point they make have been outside of the folder, but I can't remember for sure. It could have been that moving it into a folder caused it to need to re-authenticate after a restart.

**Comment by fredemmott** [comment]
So, I think this is related to folders: there doesn't seem to be a way for the plugin to tell the difference between "I deleted the actions" and "I changed folders". The 4.1 changes should make fixing this relatively straightforward

**Comment by fredemmott** [comment]
This should be fixed in v2.0: https://github.com/fredemmott/StreamDeck-Discord/releases/tag/v2.0

**Comment by ITensEI** [comment]
Installed v2.0. Issue not fixed. 

Re-created the app in Discord to use new ID/key.
Installed the app.
Pasted App ID - it asked to authorize in Discord
Pasted Key - again asked to auth
Buttons still don't work

**Comment by fredemmott** [comment]
Can you share a screenshot of the 'oauth2' page on the discord developer portal? This part in particular:

<img width="932" alt="screen shot 2019-03-02 at 4 56 18 pm" src="https://user-images.githubusercontent.com/360927/53689488-20c20980-3d0c-11e9-878d-4c9864a0f1b5.png">

**Comment by ITensEI** [comment]
Same as yours. I did notice it was set to http:// earlier, but even after correcting it no dice.

![image](https://user-images.githubusercontent.com/9561099/53689546-9b3f5900-3d0d-11e9-9a83-6daa358393ee.png)

**Comment by fredemmott** [comment]
The `/` at the end  - after `localhost` - is required; sorry, Discord is super-picky about this.

> Pressing the Relink button doesn't do anything that I can see nor make it work.

It deletes the oauth token and refresh token; if it does nothing, there's no oauth token.

If the `/` at the end doesn't fix it, given Discord is prompting you, the App ID is definitely correct; there's a few reasons why it might not be able to get an oauth token:
- copy-paste problem with the app secret. Try pasting into notepad or similar to make sure that your browser's copied it correctly -  for example, maybe you're getting extra spaces around it
- incorrect oauth configuration (e.g. the missing `/`)
- blocked access to the API. This is extremely unlikely, but to test, open https://discordapp.com/api/oauth2/token in your browser - you should see something like `{"code": 0, "message": "405: Method Not Allowed"}`

**Comment by ITensEI** [comment]
Okay I added the `/` and made sure to copy paste the key correctly - nothing.
I then created a new key and copied it again and that got Discord to ask for Auth again and this time now it's working. I'll see if it survives a reboot.

**Comment by fredemmott** [comment]
Thanks; I can change relink to do something even if there’s no auth token.

**Comment by ITensEI** [comment]
Doesn't survive the reboot. Have to re-auth using the Relink button. Probably would be best to have it show some sort of indication that it did something even if didn't.

**Comment by fredemmott** [comment]
Ok, I managed to reproduce this *once* by:

1. quit discord completely
2. quit streamdeck
3. start streamdeck
4. spam the button like crazy
5. wait 5 seconds
6. start discord

However, I could only make this go wrong once. I've tried a bunch and it usually ends up connecting fine. If someone's able to figure out reliable steps to reproduce, that'll make fixing this properly much better.

**Comment by fredemmott** [comment]
Acutally, closing in favor of #2
